version: '2'

services:

  buildozer:
    privileged: true
    image: guysoft/p4a:p4a-py3-api28ndk21
    #build: .
    # For development uncomment this and comment the image name above
    #build: .
    container_name: buildozer-test
    tty: true
    entrypoint: /bin/sh
    volumes:
      - ./:/buildozer/
      - ../python-for-android:/p4a
      - /dev/bus/usb:/dev/bus/usb 
      - /tmp/.X11-unix:/tmp/.X11-unix
