#!/usr/bin/env bash
git clone https://github.com/guysoft/kivy-external-storage-permission.git
cd kivy-external-storage-permission
sudo docker-compose up -d 
sudo docker exec -it -u 0 buildozer-test pip3 install https://github.com/kivy/buildozer/archive/master.zip
./docker_build
./docker_debug

